version: "3.9"
services:

  postgres:
    image: postgres:14
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: example
    deploy:
      resources:
        limits:
          memory: 1g
    healthcheck:
      test: CMD pg_isready -U postgres --dbname=example
      interval: 5s
      timeout: 5s
      retries: 10
